### ISSUE TITLE
CAP: Code lua errors and warnings

### ISSUE THREAD

**Issue by zachary-moote-personal** [RafaelDeJongh/cap#102]
Hi, 
I am receiving 2 errors and a warning in the 'problems' section of gmod, specifically CAP: Code.

Here are the details:
[CAP: Code] lua/stargate/shared/capcheck.lua:408: attempt to call field 'RelativePathToFull' (a nil value)
    1. unknown - lua/stargate/shared/capcheck.lua:408
        2. include - [C]:-1
            3. Load - lua/autorun/stargate.lua:128
                4. unknown - lua/autorun/stargate.lua:153
 [CAP: Code] lua/stargate/shared/capcheck.lua:408: attempt to call field 'RelativePathToFull' (a nil value)
    1. unknown - lua/stargate/shared/capcheck.lua:408
        2. include - [C]:-1
            3. Load - lua/autorun/stargate.lua:128
                4. unknown - lua/autorun/stargate.lua:153
  [CAP: Code] Warning! A net message (CAF_Start_false) is already started! Discarding in favor of the new message! (_SGCUSTOM_GROUPS)
    1. unknown - lua/stargate/server/init.lua:58

**Comment by TheMerkyShadow** [comment]
The error is regarding util.RelativePathToFull. Which is now a deprecated function and was removed in cap [here](https://github.com/RafaelDeJongh/cap/commit/38c947d9d42410961ef568f1f26d9f6a883e9c2b) 

Solution. Update CAP

**Comment by zachary-moote-personal** [comment]
> The error is regarding util.RelativePathToFull. Which is now a deprecated function and was removed in cap [here](https://github.com/RafaelDeJongh/cap/commit/38c947d9d42410961ef568f1f26d9f6a883e9c2b)
> 
> Solution. Update CAP

Oh, I see. Is the steam workshop collection not synced with the git repo?

**Comment by TheMerkyShadow** [comment]
> Oh, I see. Is the steam workshop collection not synced with the git repo?

According to the workshop [here](https://steamcommunity.com/sharedfiles/filedetails/?id=175394472) it was last updated on Jan 27, 2020 @ 7:43am

**Comment by zachary-moote-personal** [comment]
> > Oh, I see. Is the steam workshop collection not synced with the git repo?
> 
> According to the workshop update note it is newer but still erorrs. Your just going to have to wait until another developer investigates

Ok, thank you!

**Comment by TheMerkyShadow** [comment]
@zachary-moote-personal Its probably best you left this issue open until they close it

**Comment by AlexALX** [comment]
i'll try to push minor update to cap, and yes git version was updated

**Comment by AlexALX** [comment]
Ok update was pushed. Please recheck if it works fine now. Thanks.

**Comment by zachary-moote-personal** [comment]
> Ok update was pushed. Please recheck if it works fine now. Thanks.

Yes, those errors have gone away now! Thank you!
