### ISSUE TITLE
Train Teleporting Trouble

### ISSUE THREAD

**Issue by LonkTheMan** [RafaelDeJongh/cap#104]
I want to take a train through stargates, somewhat similar to what's done in The Legend of Zelda: Spirit Tracks; however, even if I get the gates perfectly aligned to the same relative spots on different sections of the track (via an alignment tool), any time that I try to drive the train through, it ends up teleporting out in the top of the gate itself. For reference, I'm trying to use Sligwolf's trains, happened with both the diesel and traditional loco. I've tried looking in the settings, but there's nothing, and keeping the gate from auto-closing doesn't help either. Any ideas?
Pictures: 
[Entering with diesel engine](https://steamcommunity.com/sharedfiles/filedetails/?id=2555585283) 
[Trying to exit with diesel engine](https://steamcommunity.com/sharedfiles/filedetails/?id=2555585698)
[Entering with steam engine](https://steamcommunity.com/sharedfiles/filedetails/?id=2555586170)
[Trying to exit with steam engine](https://steamcommunity.com/sharedfiles/filedetails/?id=2555586262)

[Diesel Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=361586208)
[Steam Engine Addon](https://steamcommunity.com/sharedfiles/filedetails/?id=132174849)

Additionally, is there not a feature for 2-way teleporting because that's how it was in the show (I can't remember exactly)? If not, could it be added? Any time I try going back, whether or not it's on auto-close, you'll disappear in the event horizon.

**Comment by TheMerkyShadow** [comment]
Personally I do not believe this is the Stargate's fault. Rather I believe its the trains themselves as they might have weird hotboxes. Try the other sligwolf vehicles. If they also have issues you have your answer.

**Comment by AlexALX** [comment]
Partial teleporting (using physics cut) was always buggy and don't think anyone will fix those issues. Just go to stargate settings and disable "Enable Physics Clipping" option. this might help, but teleport will be instant on touch.

As for second question - no there is no way enable 2-way teleporting, because its NOT how stargate works in tv show. Technically there is tons of check what prevent that, so will be not easy in any way.

**Comment by LonkTheMan** [comment]
Alrighty, thanks for letting me know, and I'll try changing the settings

**Comment by LonkTheMan** [comment]
That seemed to fix it, it no longer comes out the top of the gate; Thanks for the help! I have to make sure the train is able to go in and out super straight, but other than that it works.
