### ISSUE TITLE
Asuran satellite issues

### ISSUE THREAD

**Issue by Pockets-byte** [RafaelDeJongh/cap#112]
the Asuran weapon blows itself up with it's own kawoosh when dialed
every single time

1. get Asuran satellite
2. dial
3. watch it explode with your hopes and dreams

**Comment by KvasirSG** [comment]
I am unable to replicate the issue, do you get any Lua errors when you open the game regarding CAP?

**Comment by Pockets-byte** [comment]
I can't replicate it either
seems to have been a false alarm, was a modded game with friends
I don't get any errors when testing on my own install

**Comment by Pockets-byte** [comment]
going to close this since I don't think it's a real issue after all, sorry for the wild goose chase
