### ISSUE TITLE
Error using svn

### ISSUE THREAD

**Issue by festro** [RafaelDeJongh/cap#119]
G:\Games\Steam\steamapps\common\GarrysMod\garrysmod\addons\CAP_Resources from https://github.com/RafaelDeJongh/cap_resources.git
The XML response contains invalid XML
Malformed XML: no element found at line 6465

**Comment by AlexALX** [comment]
You are using svn on git repository. Its not same. Idk if github still provide svn support, thats not our problem at all.

**Comment by festro** [comment]
That's weird because everything else downloads just fine, I use svn for spacebuild, wire, cap, and cap_fonts without issue it's just resources; it's not like it just fails either, it will download for a bit, then after a few minutes it will error out there.

**Comment by AlexALX** [comment]
I guess you need contact github support about that then, because we can't do anything with that except contact their support as well.
