### ISSUE TITLE
Arthur's mantle Easter Egg

### ISSUE THREAD

**Issue by s1m0n39000** [RafaelDeJongh/cap#129]
When I load the map of the Arthur's mantle Easter Egg everything is purple and there are ERROR everywhere...

https://www.youtube.com/watch?v=89cINjVeF-k
Rp_Stargateworldsv4_b2 *Reupload*
https://steamcommunity.com/sharedfiles/filedetails/?id=534447424

**Comment by AlexALX** [comment]
you need probably css content mounted or/and hl ep1/2 as well.

**Comment by s1m0n39000** [comment]
Thanks, now it works without errors, the map needed Half Life: Source and Half Life: Episode Two installed and mounted in the main menu of Garry's Mod
