### ISSUE TITLE
Graphical glitch with asuan satellite

### ISSUE THREAD

**Issue by BlackOfWorld** [RafaelDeJongh/cap#29]
This happened when I was testing new update.

![20170226204421_1](https://cloud.githubusercontent.com/assets/16164933/23343039/06ab6c92-fc65-11e6-9ba4-9d31aeddf670.jpg)
![20170226204428_1](https://cloud.githubusercontent.com/assets/16164933/23343040/06cd024e-fc65-11e6-90ae-3ca797bcad2c.jpg)

It's not major or game breaking, but it's just confusing.

**Comment by AlexALX** [comment]
Should be fixed in rev 494, even fix is not really good in term of optimization, but better that nothing.
