### ISSUE TITLE
Ring Transporter Transport PermaProps

### ISSUE THREAD

**Issue by Noname12345GER** [RafaelDeJongh/cap#35]
Ive been using this Prop "models/props_phx/huge/tower.mdl"
The Rings are Porting the entire Prop.
PermaProps is Transforming props to prop_dynamic.

**Comment by AlexALX** [comment]
What is "PermaProps"? Also about big props - its engine limitation, you can blacklist it via own hooks on server side. 

https://github.com/RafaelDeJongh/cap/wiki/Lua-hooks#misc
StarGate.Rings.TeleportEnt

**Comment by Noname12345GER** [comment]
Thank you for taking the time. PermaProps is a Workshop Addon with can "save" Props on the map. After a cleanup they get spawned on the saved Position as prop_dynamic.

Can't you make a function with checks if the prop is welded with the Rings itselve?

**Comment by AlexALX** [comment]
> PermaProps is a Workshop Addon with can "save" Props on the map. After a cleanup they get spawned on the saved Position as prop_dynamic.

Are you sure that this is cap issue? Please note that in cap there is own gatespawner what can save and spawn props welded to rings/stargates etc. This isn't bug in this case as its feature and conflict with another prop saving addon.

**Comment by AlexALX** [comment]
In rev 495 i added options to disable spawn/save props by gatespawner, and i hope this will fix your issue.
