### ISSUE TITLE
Shield Core Not Working Please Help

### ISSUE THREAD

**Issue by DinnerBeef** [RafaelDeJongh/cap#36]
So Yea I Can Not Hit E On The Shield Core It Does Nothing What So Ever 

I Have Tried Everything -- Removing Space Build

**Comment by AlexALX** [comment]
Did you tried to do like on this video? https://youtu.be/IyxPLp0lvk4?t=275

**Comment by RafaelDeJongh** [comment]
Yea we expected people having this "issue" but well it's actually intended that as an actual feature. So the Changelog and Video will probably solved your "problem".

**Comment by DinnerBeef** [comment]
thanks
