### ISSUE TITLE
CGC SCREENS

### ISSUE THREAD

**Issue by DinnerBeef** [RafaelDeJongh/cap#37]
i have tired everything i can to get the screens to accept the code to get off for some reason i can not hit the enter key which i have set to many different things  

Edited Image "Might Help" https://puu.sh/uJ2BI/afd192294c.png

**Comment by Tyenkrovy** [comment]
I actually suspect it was broken by the February 2017 security hotfix, which was meant to fix an issue that allowed malicious clients to crash game servers. It may have had the side-effect of preventing certain bits of client-side LUA code from executing. This would explain why I've seen reports of the SGC screens working fine on servers with CAP installed, but not working in single player: in single player, _everyting_ is client-side.

**Comment by DinnerBeef** [comment]
um it not working on a local server so i mean

**Comment by Tyenkrovy** [comment]
Yeah, I just tested my theory with a local server myself and it didn't work. I think it's still possible that the security hotfix borked it, though, given the timing.

**Comment by Tyenkrovy** [comment]
So, I kept at this, and I figured out that the latest Wiremod update appears to be what broke the SGC Screens. I unsubscribed from the workshop version and deleted the .gma file from my addons folder, then got hold of a 7 month old version of Wiremod from github, and now it works fine.

**Comment by DinnerBeef** [comment]
so any idea when a fix will be out for this

**Comment by Tyenkrovy** [comment]
If I were more knowledgeable about LUA scripting, I might try to fix it myself. I guess we'll have to wait for AlexALX or one of the others to have time to look at it. In the mean time, using the old-workshop branch of Wiremod restores the functionality, at the expense of reverting whatever else the latest update changed.

**Comment by AlexALX** [comment]
I'm not sure when, i'm busy in near few weeks, and have no any motivation to check cap.

**Comment by CryptAlchemy** [comment]
Having the same issue; I'll take a look at the code and see if I can fix it myself. If I succeed, I'll make a pull request.

**Comment by CryptAlchemy** [comment]
UPDATE: Fixed it on my local game. Going to push an update.

**Comment by CryptAlchemy** [comment]
Okay, created the pull request. Now it's all you, Rafael & AlexALX :)

**Comment by AlexALX** [comment]
https://github.com/wiremod/wire/issues/1354
