### ISSUE TITLE
Lucian Door Opener not working

### ISSUE THREAD

**Issue by MakeLord95** [RafaelDeJongh/cap#38]
I did everything shown on the changelog video, and I can't get Lucian Door Opener to work. It just vanishes when i place it on the door... 

Any help?

**Comment by AlexALX** [comment]
Check pls console, is there anything when you placing it? If yes - copy paste here.

**Comment by MakeLord95** [comment]
There's nothing printed in console

**Comment by AlexALX** [comment]
If you holding E after place on doors, then just press once it. As it will be back to inventory when hold E. Can't help with this bug as can't reproduce on my pc and server.
