### ISSUE TITLE
Daudalus HUD Broken

### ISSUE THREAD

**Issue by flamedramon** [RafaelDeJongh/cap#46]
Im not sure if this page is even still active but the hud for the daudulus (i probably mispelled that) doesnt have meters for the stats its supposed to display

**Comment by AlexALX** [comment]
I think its not broken, this is just static texture and never work like you might think.

**Comment by flamedramon** [comment]
Ok because I'm videos I have seen little bars that appear or disappear based on the status the hud is supposed to be displaying

**Comment by AlexALX** [comment]
What screen resolution you have? as possible that is something not work on some resolutions, in any case deadalus is very old thing and in half-broken stage, so no any fixes/improvements will added to it.

**Comment by flamedramon** [comment]
1920 x 1080

**Comment by RafaelDeJongh** [comment]
In general the Daedalus was actually never finished, it was re-added after massive requests but in general it's still an unfinished vehicle. Even though we would like having someone to look into it and actually expand/fix the whole thing to a proper state, I do not think anyone will do this and as the main CAP team has disbanded no future updates regarding this entity will be provided by the main team itself.

Contributions are as always more than welcome! But besides that I'll be closing this issue as further discussion regarding this entity will not change much either way.
