### ISSUE TITLE
Call Fowarding Device

### ISSUE THREAD

**Issue by Matspyder51** [RafaelDeJongh/cap#53]
Hi, I have some time for the cap right now, I wan't to update the CFD to be like in the tv show (Redirect to an other gate) but I don't find the code where you tell to the Event Horizon to bring back the player at the start Gate, If you can tell me where it is, thanks

**Comment by AlexALX** [comment]
Hello, i think it is here: https://github.com/RafaelDeJongh/cap/blob/master/lua/entities/event_horizon/modules/teleport.lua#L147

But there is other places with check like https://github.com/RafaelDeJongh/cap/blob/master/lua/entities/event_horizon/init.lua#L792 and after that checks with "bcfd" variable... So it can be hard to modify that part.
