### ISSUE TITLE
Antarctica Gate System

### ISSUE THREAD

**Issue by viral32111** [RafaelDeJongh/cap#54]
Ever since the SGC screens were added i've always wanted a system like the Antarctica Gate from SG-1, Where if you have 2 SG-1 Stargates with the same address, and same group. If you tried dialing out from one you would get a busy signal, Also a nice thing to add with that would be DHD's have priority over SGC Computers, So it would be almost the same as the episode "Solitudes" (S1 EP18).

**Comment by AlexALX** [comment]
We don't add new content anymore, because team is disbanded. Currently we can do only major fixed for keep cap working.

**Comment by Person-For-Sale** [comment]
You can do this, you just need to use an Atlantis gate.

**Comment by Piehthyte** [comment]
Sad to see the slow death of the best Stargate mod around.
