### ISSUE TITLE
No language files found.

### ISSUE THREAD

**Issue by FusionLord** [RafaelDeJongh/cap#55]
Using Workshop version, I also tried the github version to confirm that the language files existed.
Console:
`LANGParser:new - File lua/data/language/en/stargate.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/cs/stargate.lua does not exist!
LANGParser:new - File lua/data/language/cs/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/cs/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/cs/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/cs/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/de/stargate.lua does not exist!
LANGParser:new - File lua/data/language/de/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/de/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/en/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/es-es/stargate.lua does not exist!
LANGParser:new - File lua/data/language/es-es/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/et/stargate.lua does not exist!
LANGParser:new - File lua/data/language/et/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/et/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/fr/stargate.lua does not exist!
LANGParser:new - File lua/data/language/fr/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/fr/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/fr/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/fr/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/hr/stargate.lua does not exist!
LANGParser:new - File lua/data/language/hr/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/hr/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/hu/stargate.lua does not exist!
LANGParser:new - File lua/data/language/hu/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/hu/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/hu/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/hu/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/nl/stargate.lua does not exist!
LANGParser:new - File lua/data/language/nl/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/nl/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/ru/stargate.lua does not exist!
LANGParser:new - File lua/data/language/ru/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/ru/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/ru/stargate_settings.lua does not exist!
LANGParser:new - File lua/data/language/ru/stargate_tools.lua does not exist!
LANGParser:new - File lua/data/language/sv-se/stargate.lua does not exist!
LANGParser:new - File lua/data/language/tr/stargate.lua does not exist!
LANGParser:new - File lua/data/language/tr/stargate_cap.lua does not exist!
LANGParser:new - File lua/data/language/tr/stargate_errors.lua does not exist!
LANGParser:new - File lua/data/language/tr/stargate_settings.lua does not exist!
`
![Image](http://i.imgur.com/AayqgUE.jpg)

**Comment by AlexALX** [comment]
Do you use development version of garrys mod?
