### ISSUE TITLE
EHType doesnt change via wire(or instructions not clear)

### ISSUE THREAD

**Issue by xESCOx** [RafaelDeJongh/cap#57]
i cant seem to figure out how to get the horizon type to change with wire. i want to save a dupe with the type wired to an e2 but i dont know the __*strings* required__ to change it. ive already tried "sg1","infinity",and "universe" capitalized and otherwise. me and a friend have combed throught the code but we cant find anything to help.

**Comment by AlexALX** [comment]
Hm... It should be like you wrote. I'll check it.

**Comment by AlexALX** [comment]
Ok, i checked this and it is a bug. Will be fixed in next version.

**Comment by AlexALX** [comment]
Should work now.
