### ISSUE TITLE
Minor Bugs and Issues

### ISSUE THREAD

**Issue by CruaverVoidDrake** [RafaelDeJongh/cap#59]
1. The LSD is really bad for figuring out where people are and is often significantly off center. It would be nice if it made a map overlay in black and teal with dots that show life signs.
2. The Sodan Cloak as well as all other cloaking methods do not prevent the players shadow from showing. Furthermore the Sodan Cloak in particular drains health too fast. And the phase cloak of Arthur's Mantle does not prevent one from being shot by other players, plus it still allows those phased to attack others.
3. The Anti-prior device doesn't stop the player that spawned it from no-clipping. Since it's an omni-directional type item it shouldn't have some special immunity for the player.
4. Black Hole, needs to have more range on what it can eat. Sometimes it just picks stuff up and throws it away. Example: Debris from shield scanners.
5. The Shield Core needs to also have the ability to have an enhanced buffer like an asgard shield that can essentially become more powerful the more energy it can hold. Plus what it blocks is generally unpredictable. And it could also have a containment ability like the stool.
6. Dakara Superweapon needs to include the new replicators, but that's less a bug and more a compatibility concept.
7. The goa'uld hand device's push effect can sometimes cause errors when applied against props.
8. Jaffa Staff, the staff is far too powerful relative to the Ori Staff which is suppose to be made with ascended knowledge. The Jaffa Staff should likely be around 50-75 damage and the Ori staff around 90-125 damage. Based on how Jaffa staff blasts are easier to survive in the show than Ori staff blasts. Plus the Jaffa staff also has an explosive radius which causes it's damage to be a lot more devastating.
9. Wraith Blaster should by default stun.
10. Minidrone platform should have a range about 5 times bigger for the pendant control.
11. The Ori Satellite shouldn't have the shields and weapon buffers linked.
12. The Teltak is suppose to have shields, maybe weapons but the only evidence is that they have shields as the only weaponized ones were the beam weapon one and the bounty hunter one.
13. Death Gliders shouldn't fall just because they stop. They've been seen as being able to hover.

And that's about it for what I find as bugged or incomplete.

**Comment by viral32111** [comment]
The 3rd point you made can be fixed in the context menu options, Hold C and right click on the device and theres an option to set it to target everyone, everyone but you, or just friends.

**Comment by AlexALX** [comment]
Sorry, but we don't accept requests anymore, because team is disbanded. We can only do simple bug fixes for keep cap working with gmod updates. But fell free to make pull requests if you want improve cap.

**Comment by CruaverVoidDrake** [comment]
If it's down to just basic bug fixes then can you at the least fix the fonts? I'm on a mac, so the fonts don't really work too well…at all.

**Comment by AlexALX** [comment]
About fonts - its can be issue with gmod, because in windows it work without problems, but on linux it wont in some distributes - you need to install font system-wide and only after that fonts start working. So same can be with macos.

**Comment by CruaverVoidDrake** [comment]
Does that mean I need to install the fonts on the computer as well? Because I installed the fonts both as a mod as well as in garry's mod's font folder.

**Comment by AlexALX** [comment]
You can try that, at least on linux this fixes problem.

**Comment by CruaverVoidDrake** [comment]
I tried installing the font in garry's mod, as a mod itself in the addons folder, as an independent font on my computer and user's systems. None of these worked.

**Comment by AlexALX** [comment]
Does font work inside stargate menu? Anyway i don't own any mac so can't test it at all.

**Comment by CruaverVoidDrake** [comment]
Stargate menus, I assume you mean the fonts for the gate addresses. Yes they do.
