### ISSUE TITLE
 puddle jumper 

### ISSUE THREAD

**Issue by bont1** [RafaelDeJongh/cap#60]
when I'm in the puddle jumper I can see my character moving,  when I click it I can still see my character

**Comment by viral32111** [comment]
Could you be more specific? When your actually in it flying it, or just moving it? How can you see your character? As in third person or you can see the inside of its face?

**Comment by AlexALX** [comment]
This is probably due to conflicting addons, please check it just with cap and nother else. I'm closing this, if you will find reason fell free to open it again.
