### ISSUE TITLE
Jaffa issue

### ISSUE THREAD

**Issue by YouCa2016** [RafaelDeJongh/cap#62]
Hello!
I mentioned this before in some other thread but I got no answer so I'm reposting this.
The Jaffa NPC does not shoot, neither does any other NPC's I give the Staff Weapon. Most other weapons are bugged that way, too, the only NPC I know does not bug when I give it a CAP weapon is the Metro Police. Other CAP NPC's work properly.

**Comment by YouCa2016** [comment]
Also, my game suddenly stopped using the gatespawners. (I'm sure this is clientside) If anyone knows how to, I don't know, for example reset it without having to reinstall the whole game I'd be very grateful.

**Comment by viral32111** [comment]
@YouCa2016 Are you playing on a map with gate spawners? Do you have it enabled in the CAP admin menu?

**Comment by AlexALX** [comment]
@YouCa2016 About gatespawner yea check what viral32111 said. As for NPC's - its source engine (gmod) problem, only metro police can use scripted weapons. And when you spawning cap npcs they become as metro police with changed model.

**Comment by YouCa2016** [comment]
They should've worked fine, I finished reinstalling the game, unsubscribing all the addons and removing everything but configs of CAP, some E2's and my  AdvDupe2's and it finally worked.
And my LSD graphic(?) bugs and it's screen is pitch black.
Also, I would like to know if you're gonna fix the Jaffa because even they don't shoot. It's a problem with the staff weapon itself I think.


If anyone cares about the main issue details:

 I checked it on cloudwalk (which by the way I like a lot) and construct, so no possibility of anything like no gatespawner map. No gatespawners worked, at first I tried reloading the specific gatespawner, redownloading the CAP, when all that didn't work I tried removing all the CAP addons and deleting their files before yet another redownload. Still nothing. (Note that the stargates themselves worked fine, just no gatespawners. It was very annoying on any maps with stargates as the main way to travel.) It must've been another addon what caused the gatespawners to not work.

**Comment by viral32111** [comment]
@YouCa2016 Do the gate spawner files have the correct formatting? Are they in the correct directory ( `garrysmod/lua/data/gatespawner_group_maps/` ) and do they have the file extension `.lua`?

Try creating your own gate spawner and seeing if this works, When you press the create button follow the instructions in the menu that appears.

**Comment by YouCa2016** [comment]
@viral32111 They should work fine. Even the originally implemented ones did not work. Now they do.
Also, I do not use addons conflicting with CAP, or at least I thought so...
I'm gonna deactivate everything but CAP and see if it works with the Jaffa.

**Comment by YouCa2016** [comment]
Even after using only Spacebuild, wiremod and CAP they still just move like they were shooting, but not shoot. As I said, I reinstalled the game and removed the addons once, and before this computer I had this issue on two more, so I son't think it's a clientside problem. If it is, I have no idea what could cause it.

**Comment by viral32111** [comment]
Are you using the development version of Garry's Mod?

**Comment by YouCa2016** [comment]
That has nothing to do with the issue but I know no other place I could ask that question.
What is the red-illuminated control chair base texture for?

**Comment by viral32111** [comment]
Personalisation?? I don't think there was ever a red lit control chair in the series, I think it's there just for aesthetics.

**Comment by AlexALX** [comment]
I'm closing this issue as i found reason and it will be fixed in next cap version.
