### ISSUE TITLE
SGC Screen stays Black

### ISSUE THREAD

**Issue by TomTomYT** [RafaelDeJongh/cap#65]
So i spawned a SGC Screen and Server, and turned him on but the Screen stays Black and i can't see anything on it, but my Friends on the Server can see it.

EDIT: I can see stuff on the Screen when i open the main menu, but it gets black again when i close the Menu.

**Comment by AlexALX** [comment]
Its known issue with discord overlay - it broke all source engine render targets including in gmod and sgc screens. You must disable it for play with SGC Screens. I'm closing this as its not cap issue.
