### ISSUE TITLE
Issue With ShieldCore

### ISSUE THREAD

**Issue by LeiLeiSvines** [RafaelDeJongh/cap#70]
I've tried multiple times but for some reason there is an issue with the shield core. I hit E on the device(even when receiving power) but the shield core menu doesn't pop up. I've even tried overriding using the wire tool but nothing wants to work.

**Comment by AlexALX** [comment]
You must press E on button with form of star. You can see what i mean here: https://youtu.be/IyxPLp0lvk4?t=274
