### ISSUE TITLE
stargateDHDPressButton("DIAL") ?

### ISSUE THREAD

**Issue by Skyrox** [RafaelDeJongh/cap#71]
according to the lua, doing stargateDHDPressButton("DIAL") with E2 should press the center button? but it doesn't do anything? the is an address inputted into the DHD and the only button left to press would be the center button.

**Comment by AlexALX** [comment]
It should be not "DIAL", it should be enter (what is new line char i think or so)

**Comment by Skyrox** [comment]
Ah ok, ya so "\n" worked, thanks, was going through the lua wondering why lol
