### ISSUE TITLE
Gatespawner and Expression (Advanced) 2 don't work for for admins

### ISSUE THREAD

**Issue by Reginald-Halifrax** [RafaelDeJongh/cap#72]
I was attempting to design a script with Ea2 with a simple goal, a chat operated DHD of sorts, Simply say "Dial 'address'" in chat and you are on your way.

Besides several hundred failures of finding the entity i eventually found a method good enough.

I can not dial gates via "entity.stargateDial", or much of ANYTHING using "entity.*", UNLESS i've spawned the gate. it works 100% of the time. if the Gatespawner spawns the gate. its inoperable.

**Comment by AlexALX** [comment]
Unfortunately, this restriction of rights to prevent access to the gates that are not yours. So basically its not possible to control gatespawner gates via e2/e2a except wiring to inputs (as physical access).

**Comment by Reginald-Halifrax** [comment]
Seems a bit annoying being the server owner and not being able to operate the gates, why not a system that allows a Ea2 chip access to a gate if it has the password to do so or something? I'm sure RP servers who have teams of people handling their own gate would appreciate that sort of thing.

Not saying i dont get the restriction to avoiding minging, but as said above, why not a password system attached to the gate? (i get it if thats too much of a hastle to program in, just my suggestion.)

Thanks for the reply regardless!

**Comment by AlexALX** [comment]
I don't think password protection would work properly, as via e2/e2a you can brutforce it pretty fast (as you don't have limits except e2 quota), unless you set extremely long password. and actually if you are admin then you should still have access to gatespawner gates, do you setup yourself properly as admin?

**Comment by Reginald-Halifrax** [comment]
Good point... And i'm set as super admin, i can access the gatespawner gates manually but not with entity cast E2a.

maybe instead the gate could ask for the gate owner's SteamID before proceeding to execute?

**Comment by TheMerkyShadow** [comment]
#AlexALX the best way to do this is changing e2's isOwner to be overwritten by gmods internal IsSuperAdmin. 

Otherwise the server would need to override it themselves.

**Comment by TheMerkyShadow** [comment]
Im pretty sure that doesn't account for the way e2 works

**Comment by Reginald-Halifrax** [comment]
This is [my E2a script](https://www.dropbox.com/s/0omdzp1ql0v5uls/Stargate_Chat_Dialer.txt?dl=0) that I slapped together,  it works great with stargates I spawn on the spot for testing, but not with the gatespawner gates.

I don't have any addons that do prop protection or anything like that, I only play with friends so prop protection was unnecessary.

**Comment by TheMerkyShadow** [comment]
We are well aware of the problem it's because the stargate.dial e2 function doesn't currently have an overdrive admin/superadmjn function. whether Alex wants to add that is up to him.

**Comment by AlexALX** [comment]
@TheMerkyShadow can you provide more details about what you talking? Where exactly i need to override it? On e2 side or what?

**Comment by TheMerkyShadow** [comment]
I'm sorry that im on mobile.

https://github.com/RafaelDeJongh/cap/blob/master/lua/entities/gmod_wire_expression2/core/custom/stargate.lua

lines:

596, 601, 606, 615

There is no check pointing to the ENT.CanModifyGate. So it cannot be overwritten.

**Comment by Reginald-Halifrax** [comment]
Unrelated: I really must thank you guys for being so co-operative in investigating this issue, so used to finding devs that want to instead just blame you and say its your fault and such. It's a breath of fresh air to find the good devs.

**Comment by Reginald-Halifrax** [comment]
i said "you guys" meaning both of you lol

**Comment by AlexALX** [comment]
@TheMerkyShadow ah that thing... Ok thank you for information, and actually i think there is wrong condition - it should check "not isOwner(self,this) and not self.player:IsAdmin()" instead of current check, but i'm not sure yet (as there is already not ( ) for both condition before and technically should do same), anyway this issue actually about e2a not regular e2, so take look this: https://github.com/RafaelDeJongh/cap/blob/master/lua/expadv/components/custom/stargate.lua#L541

This extension was written not by me so i'm not sure what exactly it doing here.

**Comment by TheMerkyShadow** [comment]
exactly @AlexALX.

You should add an exception [ this.CAP_CanModify(self.player) ]
Because [ not(isOwner(self,this) ] will never work with gatespawn since its owned by the world.
This is where I think the original problem occurs.

**Comment by TheMerkyShadow** [comment]
The problem exists in both e2 and e2a due to the logic. However, I don't really care for e2a as it's more trouble than it's worth especially since its support was dropped.

**Comment by Reginald-Halifrax** [comment]
Rusketh has been poking around making a 3rd so hopefully that goes well.

**Comment by Reginald-Halifrax** [comment]
@AlexALX so have we come to a resolution? or are gatespawner gates doomed to be inaccessible to superadmin e2 and e2a scripts?

**Comment by TheMerkyShadow** [comment]
@Reginald-Halifrax The problem has been identified its a relatively simple fix at least for e2. Just give @AlexALX some time. If he doesn't do it within a few days, I can always take a crack at the fix myself.

**Comment by Reginald-Halifrax** [comment]
i was just askin' if it was being worked on lol. i am in no rush.

**Comment by AlexALX** [comment]
yes, but as i said it should be ignored when you are admin.

**Comment by TheMerkyShadow** [comment]
cool

**Comment by Reginald-Halifrax** [comment]
I did a check to see if E2 chips work fine rather than E2a. E2 chips work perfectly fine. so its only E2a giving the issue.

**Comment by TheMerkyShadow** [comment]
@Reginald-Halifrax I highly doubt that. Post the e2 code.

**Comment by Reginald-Halifrax** [comment]
@inputs Button
@outputs 
@persist  SG:entity


if (Button == 1) {SG = owner():aimEntity()
SG:stargateDial("TOWER0")
}

literally bottom of the barrel script to test it. dialed just fine.

**Comment by TheMerkyShadow** [comment]
https://github.com/wiremod/wire/blob/e4d74f04cc2964a76fb2b3f901b0d9e9ef2faee2/lua/entities/gmod_wire_expression2/core/e2lib.lua#L187

Lol it only works in single-player. Try it on a multiplayer server.

@AlexALX will probably laugh at this

**Comment by Reginald-Halifrax** [comment]
that _was_ a multiplayer server. again. super admin in it.

**Comment by TheMerkyShadow** [comment]
I just tested it myself....

**Comment by Reginald-Halifrax** [comment]
see now im just confused. i got it to dial.

**Comment by TheMerkyShadow** [comment]
join this server and try to do it.
77.48.52.4:27015

**Comment by TheMerkyShadow** [comment]
@AlexALX he's right. But sometimes the e2's code can be glitchy as well but that really isnt the problem atm. I tried a few fixes of my own for e2a by adding an admin excemption and I couldnt figure out why it wasnt working.

**Comment by AlexALX** [comment]
can someone tell if this still issue with e2a after this years?
