### ISSUE TITLE
Gatespawner parsing issue

### ISSUE THREAD

**Issue by taikowolf** [RafaelDeJongh/cap#74]
I have been attempting to create a working Gatespawner for a couple of maps I enjoy greatly, but I have been getting this error consistently:

INIParser:parse - Parse error in file lua/data/gatespawner_group_maps/gm_supersizeroom.v2.lua at line 1 near "??[StarGate GateSpawner Error:
Your gatespawner file is invalid.
Please create new gatespawner.

INIParser:parse - Parse error in file lua/data/gatespawner_group_maps/gm_madgrass_v6.lua at line 1 near "??[StarGate GateSpawner Error:
Your gatespawner file is invalid.
Please create new gatespawner.

While this error is flashing, the map has no Stargates, DHDs or ramps spawned in. Even when I have only a couple of Stargates in the map, the same parsing error comes up.

Apologies if this is the wrong place to put difficulties such as these.

**Comment by AlexALX** [comment]
did you edit your gatespawner files with editor? You probably did save it in UTF8 with boom, and you should save it without boom!

**Comment by taikowolf** [comment]
I've actually been saving it in Unicode via Nodepad, since that's what the guide I was using did. I saved it to UTF-8 instead with the same method, and it works great now. Thanks for the quick reply. 😃
