### ISSUE TITLE
Ring issue

### ISSUE THREAD

**Issue by SteamDoge9000** [RafaelDeJongh/cap#76]
Hi i came hear to ask for some help on the rings not being able to dial 
im not sure why this is happening on the server but i am looking for some answers
it would relay mean a lot if you can help me solve this mess>

**Comment by SteamDoge9000** [comment]
i got this error message when i tried using wiremod with it
can you guys make any heads or tales out of it

sv: Wire error (Entity [376][ring_base_ancient] by Player [3][Doge 9000]):
lua/autorun/server/cpt_meta.lua:726: attempt to index a string value with bad key ('GetPos' is not part of the string library)
stack traceback:
	[C]: in function 'error'
	lua/includes/extensions/string.lua:297: in function '__index'
	lua/autorun/server/cpt_meta.lua:726: in function 'FindNearest'
	lua/entities/ring_base/init.lua:449: in function 'StartSequence'
	lua/entities/ring_base/init.lua:515: in function 'Dial'
	lua/entities/ring_base/init.lua:488: in function <lua/entities/ring_base/init.lua:484>
	[C]: in function 'xpcall'
	lua/wire/server/wirelib.lua:57: in function 'TriggerInput'
	lua/wire/server/wirelib.lua:529: in function 'Wire_TriggerOutput'
	lua/entities/gmod_wire_button.lua:168: in function 'Switch'
	lua/entities/gmod_wire_button.lua:98: in function <lua/entities/gmod_wire_button.lua:83>

**Comment by AlexALX** [comment]
Do you have other addons as well? Try disable all addons first except cap and wiremod. It looks like addon conflict or so.
