### ISSUE TITLE
Cloaking Field Generator + SGU stargate graphical bug

### ISSUE THREAD

**Issue by slava110** [RafaelDeJongh/cap#78]
Before and after using cloaking device
![20180815100331_1](https://user-images.githubusercontent.com/26705162/44135960-ba84bd3c-a073-11e8-9473-ba3e5b07fafe.jpg)

**Comment by NotThatSiri** [comment]
To provide a bit more information on this.
After disabling cloak on the SGU gate the skin changes into the dark one. After testing this I can conclude that chevrons don't light up either, the spin animation however still works
