### ISSUE TITLE
Shield Core doesnt work properly

### ISSUE THREAD

**Issue by MakeLord95** [RafaelDeJongh/cap#79]
RPG, Grenade, Asuran gate weapon and Crossbow bullets go through the shield. I tested this with only CAP, Spacebuild and Wiremod. It used to work properly but I think an update to Gmod broke this. Any chance of it getting fixed at somepoint?

**Comment by MakeLord95** [comment]
Any updates on this?

**Comment by MakeLord95** [comment]
Seems like this mod has been abandoned. I will close this issue...

**Comment by AlexALX** [comment]
@RafaelDeJongh i also receive notifications about any issues on cap github, but basically i just don't have time to check and look, while i still planned micro update for cap in previous month.

**Comment by RafaelDeJongh** [comment]
@AlexALX 

Same here, there's just not enough time to proceed with the mod, it's also not for nothing that we made it completely open source with no restrictions. 

If only people had donated and invested a bit more in the project then things would have gotten a lot better in the long run...
