### ISSUE TITLE
Stargate places Player behind Gate Sometimes.

### ISSUE THREAD

**Issue by oninoni** [RafaelDeJongh/cap#80]
Sometimes when going through a Stargate it places you behind the gate. I've searched in the code but it seems like this should not happen because the player is placed on the event horizon. 

Could this be because you get noclip for one tick? Basically flying for one tick

**Comment by oninoni** [comment]
Ok so i'm pretty sure it IS because you get noclip. You can even catapult yourself using that bug.

**Comment by TheMerkyShadow** [comment]
Yeah sounds like the player is not syncing properly all of the time. A solution could be if a player is in noclip to pre-freeze the player to prevent movement.

**Comment by oninoni** [comment]
I think the PrepareTeleport(t) Function also does not always place you in the correct position. It's all very weird.

**Comment by AlexALX** [comment]
Its known and very old bug, if someone will able to actually investigate it and find whats wrong - it will be really nice. At the moment there is no devs in cap so feel free to look into it, i might do small cap update before/after new year so..

**Comment by oninoni** [comment]
I did make a few changes. It is a timing problem as far as i can see and i've got a hacky Fix on my side. Will test it on my server and report back when it's better

**Comment by oninoni** [comment]
Ok so there's 2 Problems:

One is the Noclip:

I'm not really sure why it's there altogether.
I just replaced the Whole setting MoveType and a timer with 

`e:SetPos(pos.New);
e:SetEyeAngles(e:GetAimVector():Angle() + Angle(0,ang.Delta.y+180,0));
e:SetVelocity(vel.New);

-- For some Reason velocity needs to be set twice for it to work.
timer.Simple(0, function()
	e:SetVelocity(vel.New);
end)`

And it's working just fine.

Other one are the last 3 lines of "PrepareTeleport". They seem to offset you by the size of the object infront of the gate. Wich makes you spawn in front of the gate instead of in the horizon.

I just commented them and now it's working fine. You need to keep the return of course.

**Comment by TheMerkyShadow** [comment]
I have to come up with a better way of predicting the improper teleport before it happens. Give me some time

**Comment by oninoni** [comment]
Yeah sure. It's working on my server now and you got what i've done :P Now you do your magic

**Comment by TheMerkyShadow** [comment]
Ok this would seem to make sense in theory....to detect whether a position is in or behind the gate. And override the position for a perfect spawn.

https://github.com/TheMerkyShadow/cap/blob/patch-1/lua/entities/event_horizon/modules/teleport.lua#L233-L239

**Comment by oninoni** [comment]
Should be a lot better than the current version. You still got the Rocket Mode when Jumping and Running Through the gate tho. Because of the Noclip for one Tick. I just set the speed again in the Timer where the noclip gets removed. That fixes that

**Comment by TheMerkyShadow** [comment]
Humor me by placing a one second timer with player freeze before/after SetPos().

**Comment by TheMerkyShadow** [comment]
Well it was just for a second so it doesn't run twice.

**Comment by AlexALX** [comment]
@TheMerkyShadow  isn't your code removes thing when we may teleport inside of ground and stuck in it? Like if gate are placed bit buried and we going from normal gate to those buried gate.. I think there was check for that for prevent that. So please do more tests.

**Comment by TheMerkyShadow** [comment]
@AlexALX yeah I have no idea why I removed that.

**Comment by oninoni** [comment]
To be honest i think this will make it worse O.o

**Comment by AlexALX** [comment]
Closing this until we get proper fix
