### ISSUE TITLE
Odd dialling feature

### ISSUE THREAD

**Issue by Person-For-Sale** [RafaelDeJongh/cap#85]
So I was playing around (in-game) with a DHD and I discovered that the sequence of an address doesn't matter, as long as you have the right symbols. For example, to dial a gate with the address "SPAWNG#", you can rearrange the letters to "SAWNGP#" or "ANGWPS#".

**Comment by AlexALX** [comment]
Not an issue - stargate do use 6 star points as destination address, so it does not matter in what order you put first 6 letters. exception is only for 9 chevron dialing i think. So it exactly like was in tv show.
