### ISSUE TITLE
Workshop changes regarding latest Garry's Mod update

### ISSUE THREAD

**Issue by viral32111** [RafaelDeJongh/cap#87]
Hey, now that the file size cap on the Garry's Mod steam workshop has been removed in [the latest update](https://steamcommunity.com/gid/103582791430264201/announcements/detail/3334287173839084095) are there any plans to condense down the 31 or so CAP addons on the workshop into a single one?

The whole reason that the file size cap has been removed is to try discourage multiple addons for content and give players more ease of life when using the workshop.

I understand most developers don't like updating things on the workshop because it's a bit tediuous and it takes ages to complete (especially for big addons), I'm the same. However CAP gets such little updates anyway that it wouldn't exactly disadvantage any of the developers because there aren't any updates to push.

(I downloaded the latest cap and cap_resources, merged them then uploaded them to the workshop [here](https://steamcommunity.com/sharedfiles/filedetails/?id=1971585217) using the updated version of gmad/gmpublish just to demonstrate my point.)

**Comment by AlexALX** [comment]
Big downside of that - if we need to update small piece of code - you will redownload whole addon with this 2 GB of data. I know that cap is not updated for a while, but it might do that anyway. But, probably we can combine some parts into one, and make like 5-6 bigger parts. We will discuss with other cap team about that in near future.

**Comment by viral32111** [comment]
Then how about keeping the CAP: Code seperate from everything else? The other ~30 addons on the workshop is just CAP Resources split up into multiple addons. If you make the workshop CAP the same as the GitHub with two seperate CAP: Code and CAP: Resources addons then it'll be much easier to change the code without having to redownload/reupload the entirerty of CAP: Resources.
