### ISSUE TITLE
Question regarding stargates creation

### ISSUE THREAD

**Issue by SuperTemich2005** [RafaelDeJongh/cap#90]
Is it possible to create your own stargate?
I mean, with it's own model, size, so it could call another SG, so it would have it's own address and would be able to call/get called?

**Comment by AlexALX** [comment]
Of course you can, just copy stargate_sg1 to something else and change model etc. there is few additional stargates on workshop and can be used as example as well.

**Comment by SuperTemich2005** [comment]
Thx
