### ISSUE TITLE
Bug With Firing Textur

### ISSUE THREAD

**Issue by XCOYoshi** [RafaelDeJongh/cap#99]
![image](https://user-images.githubusercontent.com/26392051/97915197-5d4fcf00-1d51-11eb-9d00-6c4e5f6eae41.png)

I only have this problem with the Wepons from CAP. Other mod weapons work. I got the latest cap resources and the cap master install from github ps sorry for the bad english its google translate

**Comment by XCOYoshi** [comment]
Ps. Onlsy With the p90

**Comment by AlexALX** [comment]
Maybe you are running GMOD in directx 8 ? I do remember there is issues with dx8 and cap, and even much more major ones.

**Comment by XCOYoshi** [comment]
no i wos runing the higest version of DX

**Comment by AlexALX** [comment]
then probably conflict with some other addon, just checked and i don't have such issue, try isable all exccept cap/wiremod

**Comment by XCOYoshi** [comment]
In single player i dont have the Problem only on my lokal host Server

AlexALX <notifications@github.com> schrieb am Mo., 30. Nov. 2020, 12:18:

**Comment by XCOYoshi** [comment]
Fixed in the newe relese
